let permissions = {
    c:{
        me:["ticket","phone","email"],
        others:["ticket","phone","email"],
        general:["rol","area"]
    },
    r:{
        ticket:{
            me:["date","time","requester","executer","activity_date","finished_date","details"],
            others:["date","time","requester","executer","activity_date","finished_date","details"],
            general:["id","origin","status"]
        },
        user:{
            me:["id","name","last_name","dni","phone","email","birthdate","creation_date","rol","origin"],
            others:["id","name","last_name","dni","phone","email","birthdate","creation_date","rol","origin"]
        },
        permissions:true,
        area:true,
        statistic:true
    },
    u:{
        ticket:{
            me:["origin","activity_date","details","status"],
            others:["origin","activity_date","details","status"]
        },
        user:{
            me:["phone","email","rol","origin"],
            others:["phone","email","rol","origin"]
        },
        area:true,
        permissions:true
    },
    d:{
        user:{
            me:["account","phone","email","origin"],
            others:["account","phone","email","origin"]
        },
        rol:true,
        area:["email"],
        areas:true
    }
}